title: DARE Aquatics 
description: Documentation 
theme: just-the-docs

logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/logo.png"

search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
  focus_shortcut_key: 'k'

footer_content: "Copyright &copy; 2017-2020 DARE Aquatics. Distributed by an <a href=\"https://dareaquatics.com/license\">GPLv3 license.</a>"

callouts:
  danger:
    title: Danger
    color: red
  warning:
    title: Warning
    color: yellow
  note: 
    title: note
    color: blue
  
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/dareaquatics/documentation
gh_edit_branch: "main" 
gh_edit_view_mode: "edit" 
  
url: htps://docs.dareaquatics.com

aux_links:
    GitHub Repository: https://github.com/dareaquatics/documentation